### ISSUE TITLE
vad händer om filer med samma namn laddas upp två gånger?

### ISSUE THREAD

**Issue by ntijoh-daniel-berg** [ntijoh-rasmus-brandt/WTF24#2]
https://github.com/ntijoh-rasmus-brandt/WTF24/blob/509a51e4bab7e3ebd9ac2c3a445c3e47615cfe06/app.rb#L39C4-L42C1

**Comment by RaasBraa** [comment]
Nu skrivs dom över jag vet inte riktigt vad som borde hända istället. Ifall jag ska behålla original bilden istället och spara den ny uppladdade under ett annat namn och file path eller säga till användaren som laddar upp att "Det finns redan en fil med detta namn, byt namn på filen". Vad tycker du borde hända när filer med samma namn laddas upp två gånger?

**Comment by ntijoh-daniel-berg** [comment]
Man brukar ge filer ett slumpat namn när de laddas upp. Om man vill kan man spara originalnamnet i db. Då kan man, om någon vill ladda ner filen, sätta tillbaks originalnamnet.


Se https://ruby-doc.org/stdlib-2.5.1/libdoc/securerandom/rdoc/Random/Formatter.html
